#!/usr/bin/env python3
"""
GCI (Grid Convergence Index) and Richardson extrapolation report for Roark vs FEM
tip deflection and tip rotation.

Uses three mesh levels (n=25, 50, 100) for jobs 0,1,2 (point load) and 5,6,7 (distributed).
Outputs CSV, LaTeX table (.tex), PDF report, and console summary. Requires result dirs job_XXXX_n25, n50, n100.
Run from project root: python post_processing/verification_visualisers/deflection_tables/gci_richardson_roark_report.py
"""
from __future__ import annotations

import glob
import math
import re
import subprocess
import sys
from pathlib import Path
from typing import Final, Optional

import numpy as np

SCRIPT_DIR: Final[Path] = Path(__file__).resolve().parent
PROJECT_ROOT: Final[Path] = next(
    (p for p in SCRIPT_DIR.parents if (p / "pre_processing").is_dir()),
    SCRIPT_DIR.parents[4],
)
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(SCRIPT_DIR.parent / "roarks_formulas"))

from pre_processing.parsing.grid_parser import GridParser  # type: ignore
from roarks_formulas_point import roark_point_load_response  # type: ignore
from roarks_formulas_distributed import roark_distributed_load_response  # type: ignore

# Beam parameters (must match job material/section: E from material.txt, I_z from section.txt)
E: Final[float] = 2.1e11  # Pa (job files use 2.1e11; 2.0e11 would give ~4.76% systematic error vs FEM)
I_z: Final[float] = 2.08769e-06  # m^4
P_point: Final[float] = -500.0  # N
w_dist: Final[float] = 500.0  # N/m

# Three-grid levels: fine n=100, medium n=50, coarse n=25; refinement ratio r = 2
N_FINE, N_MED, N_COARSE = 100, 50, 25
R: Final[float] = 2.0
F_S: Final[float] = 1.25  # three-grid safety factor

POINT_JOBS: Final[list[tuple[int, str, str]]] = [
    (0, "End", "end"),
    (1, "Mid-span", "mid"),
    (2, "Quarter-span", "quarter"),
]
DIST_JOBS: Final[list[tuple[int, str, str]]] = [
    (5, "UDL", "udl"),
    (6, "Triangular", "triangular"),
    (7, "Parabolic", "parabolic"),
]


def _fmt_tex(val: float, decimals: int, dash: str = "---") -> str:
    """Format a number for LaTeX table; return dash for non-finite."""
    if not math.isfinite(val):
        return dash
    s = f"{val:.{decimals}f}".rstrip("0").rstrip(".") or "0"
    return f"${s}$"


def _write_latex_table(out_dir: Path, rows: list[dict]) -> None:
    """Generate gci_richardson_roark_deflection_rotation.tex from report rows."""
    qoi_short = {"tip_deflection_mm": "$u_y$ (mm)", "tip_rotation_deg": "$\\theta_z$ (deg)"}
    lines = [
        "% LaTeX table generated by gci_richardson_roark_report.py",
        "% Requires: \\usepackage{booktabs}",
        "% Columns: phi_1, GCI, p, r^p, Delta(phi_1,Roark) %, phi_rich.",
        "% See GCI_REPORT_TABLE_CHECKLIST.md for what else is necessary in a GCI report table.",
        "",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{GCI--Richardson extrapolation vs.\\ Roark: deflection and rotation.}",
        "\\label{tab:gci_richardson_roark_deflection_rotation}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{@{}cll r rr rr r r r rr r@{}}",
        "\\toprule",
        "Job & Load type & QoI & $\\phi_1$ & GCI$_{12}$ (\\%) & GCI$_{23}$ (\\%) & GCI$_{23}$/GCI$_{12}$ & $p$ & $r^p$ & $\\Delta(\\phi_1,\\mathrm{Roark})$ (\\%) & $\\phi_\\mathrm{rich}$ \\\\",
        "\\midrule",
    ]
    prev_job_id = -1
    for r in rows:
        load_type = r["load_type"]
        qoi = qoi_short.get(r["QoI"], r["QoI"])
        phi1 = _fmt_tex(r["phi_fine"], 4) if abs(r["phi_fine"]) < 1 else _fmt_tex(r["phi_fine"], 3)
        # Hide GCI ratio when meaningless (e.g. GCI_12 ≈ 0 gives huge ratio)
        ratio_val = r["GCI_23_12_ratio"]
        ratio_meaningless = (
            not math.isfinite(ratio_val)
            or ratio_val > 100
            or (math.isfinite(r["GCI_12_pct"]) and abs(r["GCI_12_pct"]) < 1e-5)
        )
        # When ratio is unphysical, GCI and order are not interpretable (e.g. Job 1: e21≈0 → fake zero GCI)
        if ratio_meaningless:
            gci12 = "---"
            gci23 = "---"
            ratio = "---"
            p = "---"
            r_p = "---"
        else:
            gci12 = _fmt_tex(r["GCI_12_pct"], 3) if math.isfinite(r["GCI_12_pct"]) else "---"
            gci23 = _fmt_tex(r["GCI_23_pct"], 3) if math.isfinite(r["GCI_23_pct"]) else "---"
            # Ratio, p, r^p: exactly 2 decimal places
            ratio = f"${ratio_val:.2f}$" if math.isfinite(ratio_val) else "---"
            p = f"${r['p_obs']:.2f}$" if math.isfinite(r["p_obs"]) else "---"
            r_p = f"${r['r_p']:.2f}$" if math.isfinite(r["r_p"]) else "---"
        delta_phi1 = _fmt_tex(r["error_phi1_Roark_pct"], 2) if math.isfinite(r["error_phi1_Roark_pct"]) else "---"
        phi_rich = _fmt_tex(r["phi_ext"], 4) if abs(r["phi_ext"]) < 1 else _fmt_tex(r["phi_ext"], 3)
        # Visual break between point-load (0,1,2) and distributed (5,6,7) blocks
        if prev_job_id in (0, 1, 2) and r["job_id"] == 5:
            lines.append("\\addlinespace")
        prev_job_id = r["job_id"]
        lines.append(
            f"{r['job_id']} & {load_type} & {qoi}   & {phi1} & {gci12} & {gci23} & {ratio} & {p} & {r_p} & {delta_phi1} & {phi_rich} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\medskip",
        "\\raggedright",
        "\\small",
        "\\textbf{Note.} Grids: $n_1=100$, $n_2=50$, $n_3=25$ elements; refinement ratio $r=2$; "
        "safety factor $F_s=1.25$ (three-grid): we use the standard three-grid GCI formula, and the factor 1.25 is the one recommended for that case. "
        "$\\phi_1$ = fine-grid solution; $p$ = apparent order ($p_\\mathrm{th}=2$). "
        "$\\Delta(\\phi_1,\\mathrm{Roark}) = 100(\\phi_1-\\mathrm{Roark})/\\mathrm{Roark}$; $\\phi_\\mathrm{rich}$ = Richardson extrapolate. "
        "GCI$_{23}$/GCI$_{12}$ $\\approx r^p$ in asymptotic range.",
        "\\end{table}",
    ])
    tex_path = out_dir / "gci_richardson_roark_deflection_rotation.tex"
    tex_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved: {tex_path}")


def _build_pdf(out_dir: Path) -> bool:
    """Run pdflatex on the standalone document to produce the PDF. Returns True if successful."""
    standalone = out_dir / "gci_richardson_roark_deflection_rotation_standalone.tex"
    if not standalone.is_file():
        print(f"Standalone .tex not found: {standalone}, skipping PDF.")
        return False
    try:
        for _ in range(2):
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", standalone.name],
                cwd=out_dir,
                capture_output=True,
                text=True,
                timeout=60,
            )
            if result.returncode != 0:
                print("pdflatex stderr:", result.stderr[-500:] if result.stderr else "")
                return False
        pdf_path = out_dir / "gci_richardson_roark_deflection_rotation_standalone.pdf"
        if pdf_path.is_file():
            print(f"Saved: {pdf_path}")
            return True
        return False
    except FileNotFoundError:
        print("pdflatex not found; install a LaTeX distribution to generate the PDF.")
        return False
    except subprocess.TimeoutExpired:
        print("pdflatex timed out.")
        return False


def _get_node_coordinates(grid_obj: object) -> np.ndarray:
    if isinstance(grid_obj, dict) and "grid_dictionary" in grid_obj:
        inner = grid_obj["grid_dictionary"]
        if isinstance(inner, dict) and "coordinates" in inner:
            return inner["coordinates"]
    if isinstance(grid_obj, dict) and "node_coordinates" in grid_obj:
        return grid_obj["node_coordinates"]
    if hasattr(grid_obj, "node_coordinates"):
        return getattr(grid_obj, "node_coordinates")
    raise KeyError("grid data does not contain 'grid_dictionary' -> 'coordinates'")


def _read_U_global(file: Path) -> Optional[np.ndarray]:
    try:
        vals = np.genfromtxt(file, delimiter=",", skip_header=1, usecols=1)
        if vals.size % 6:
            return None
        return vals.reshape(-1, 6)
    except Exception:
        return None


def _get_fem_tip_values(csv_file: Path, jobs_dir: Path, job_input_name: str) -> Optional[tuple[float, float, float]]:
    """Return (L, tip_u_y_mm, tip_theta_z_deg) or None."""
    grid_file = jobs_dir / job_input_name / "grid.txt"
    if not grid_file.is_file():
        return None
    U = _read_U_global(csv_file)
    if U is None:
        return None
    grid = GridParser(str(grid_file), str(jobs_dir / job_input_name)).parse()
    try:
        node_coords = _get_node_coordinates(grid)
    except Exception:
        return None
    x = node_coords[:, 0]
    if x.shape[0] != U.shape[0]:
        return None
    L = float(np.max(x))
    tip_idx = int(np.argmax(x))
    tip_uy_mm = float(U[tip_idx, 1] * 1000)
    tip_theta_deg = float(np.degrees(U[tip_idx, 5]))
    return (L, tip_uy_mm, tip_theta_deg)


def _richardson_gci(
    phi_fine: float, phi_med: float, phi_coarse: float
) -> tuple[float, float, float, float]:
    """
    Three-grid Richardson and GCI. phi_fine = value at n=100, phi_med at n=50, phi_coarse at n=25.
    Returns (p_obs, phi_ext, gci_12_pct, gci_23_pct). GCI_12 on fine grid, GCI_23 on medium.
    """
    e21 = phi_med - phi_fine
    e32 = phi_coarse - phi_med
    if abs(e21) < 1e-30 and abs(e32) < 1e-30:
        return (float("nan"), phi_fine, 0.0, 0.0)
    ratio = e32 / e21 if abs(e21) >= 1e-30 else float("nan")
    if ratio <= 0 or not math.isfinite(ratio):
        p_obs = float("nan")
        phi_ext = phi_fine
        gci_12_pct = float("nan")
        gci_23_pct = float("nan")
    else:
        p_obs = math.log(abs(ratio)) / math.log(R)
        denom = (R ** p_obs) - 1.0
        if denom <= 0 or not math.isfinite(denom):
            phi_ext = phi_fine
            gci_12_pct = float("nan")
            gci_23_pct = float("nan")
        else:
            phi_ext = phi_fine + (phi_fine - phi_med) / denom
            if abs(phi_fine) >= 1e-30:
                gci_12_pct = 100.0 * F_S * abs(e21 / phi_fine) / denom
            else:
                gci_12_pct = float("nan")
            if abs(phi_med) >= 1e-30:
                gci_23_pct = 100.0 * F_S * abs(e32 / phi_med) / denom
            else:
                gci_23_pct = float("nan")
    return (p_obs, phi_ext, gci_12_pct, gci_23_pct)


def _run_report() -> None:
    results_dir = PROJECT_ROOT / "post_processing" / "results"
    jobs_dir = PROJECT_ROOT / "jobs"
    out_dir = SCRIPT_DIR / "gci_richardson"
    out_dir.mkdir(exist_ok=True)

    pattern = str(results_dir / "job_*" / "primary_results" / "global" / "U_global.csv")
    csv_files = sorted(glob.glob(pattern))
    # by_base[base_id] = [(n, csv_file, job_input_name), ...]
    by_base: dict[int, list[tuple[int, Path, str]]] = {}
    for csv_path in csv_files:
        csv_file = Path(csv_path)
        job_dir = csv_file.parent.parent.parent
        name = job_dir.name
        m = re.match(r"job_(?P<id>\d+)_n(?P<n>\d+)_[\d\-_]+_pid\d+_[a-f0-9]+", name)
        if not m:
            continue
        base_id = int(m.group("id"))
        n = int(m.group("n"))
        if base_id not in (0, 1, 2, 5, 6, 7):
            continue
        job_input_name = f"job_{base_id:04d}_n{n}"
        by_base.setdefault(base_id, []).append((n, csv_file, job_input_name))

    # One result per (base_id, n); keep first occurrence when multiple runs exist
    n_map_per_base: dict[int, dict[int, tuple[Path, str]]] = {}
    for base_id in by_base:
        n_map_per_base[base_id] = {}
        for n, cf, jn in sorted(by_base[base_id], key=lambda t: t[0]):
            if n not in n_map_per_base[base_id]:
                n_map_per_base[base_id][n] = (cf, jn)

    rows: list[dict] = []
    all_jobs = [(j, lbl, lt) for j, lbl, lt in POINT_JOBS] + [(j, lbl, lt) for j, lbl, lt in DIST_JOBS]

    for job_id, load_label, load_type in all_jobs:
        if job_id not in n_map_per_base:
            continue
        n_map = n_map_per_base[job_id]
        if N_FINE not in n_map or N_MED not in n_map or N_COARSE not in n_map:
            for n_need in (N_FINE, N_MED, N_COARSE):
                if n_need not in n_map:
                    print(f"WARNING: job_{job_id:04d} missing n={n_need}, skipping GCI/Richardson.")
                    break
            continue

        phi_uy = {}
        phi_theta = {}
        for n in (N_FINE, N_MED, N_COARSE):
            cf, jn = n_map[n]
            out = _get_fem_tip_values(cf, jobs_dir, jn)
            if out is None:
                print(f"WARNING: job_{job_id:04d}_n{n} failed to get tip values, skipping.")
                break
            _L, uy_mm, theta_deg = out
            phi_uy[n] = uy_mm
            phi_theta[n] = theta_deg
        else:
            L_ref = _L
            # Roark tip: use 1000-point grid for all cases (distributed needs it for accurate integration)
            n_roark = 1000
            x_roark = np.linspace(0.0, L_ref, n_roark)
            if job_id in (0, 1, 2):
                roark = roark_point_load_response(x_roark, L_ref, E, I_z, P_point, load_type)
                roark_uy = float(roark["deflection"][-1] * 1000)
                roark_theta = float(np.degrees(roark["rotation"][-1]))
            else:
                roark = roark_distributed_load_response(x_roark, L_ref, E, I_z, w_dist, load_type)
                roark_uy = float(roark["deflection"][-1] * 1000)
                roark_theta = float(np.degrees(roark["rotation"][-1]))

            for qoi_name, phi_dict, roark_val in [
                ("tip_deflection_mm", phi_uy, roark_uy),
                ("tip_rotation_deg", phi_theta, roark_theta),
            ]:
                p_obs, phi_ext, gci_12_pct, gci_23_pct = _richardson_gci(
                    phi_dict[N_FINE], phi_dict[N_MED], phi_dict[N_COARSE]
                )
                if abs(roark_val) >= 1e-30:
                    err_pct = 100.0 * (phi_ext - roark_val) / roark_val
                else:
                    err_pct = float("nan") if not math.isfinite(phi_ext) else (phi_ext - roark_val)

                phi_fine = phi_dict[N_FINE]
                if abs(phi_ext) >= 1e-30 and math.isfinite(phi_ext):
                    fine_vs_rich_pct = 100.0 * abs(phi_fine - phi_ext) / abs(phi_ext)
                else:
                    fine_vs_rich_pct = float("nan")
                if (
                    math.isfinite(gci_12_pct)
                    and abs(gci_12_pct) >= 1e-30
                    and math.isfinite(gci_23_pct)
                ):
                    gci_23_12_ratio = gci_23_pct / gci_12_pct
                else:
                    gci_23_12_ratio = float("nan")
                r_p = (R ** p_obs) if math.isfinite(p_obs) else float("nan")
                if abs(roark_val) >= 1e-30:
                    error_phi1_Roark_pct = 100.0 * (phi_fine - roark_val) / roark_val
                else:
                    error_phi1_Roark_pct = float("nan")

                rows.append({
                    "job_id": job_id,
                    "load_type": load_label,
                    "QoI": qoi_name,
                    "n_fine": N_FINE,
                    "n_med": N_MED,
                    "n_coarse": N_COARSE,
                    "phi_fine": phi_fine,
                    "phi_med": phi_dict[N_MED],
                    "phi_coarse": phi_dict[N_COARSE],
                    "p_obs": p_obs,
                    "phi_ext": phi_ext,
                    "Roark": roark_val,
                    "error_ext_Roark_pct": err_pct,
                    "error_phi1_Roark_pct": error_phi1_Roark_pct,
                    "GCI_12_pct": gci_12_pct,
                    "GCI_23_pct": gci_23_pct,
                    "fine_vs_rich_pct": fine_vs_rich_pct,
                    "GCI_23_12_ratio": gci_23_12_ratio,
                    "r_p": r_p,
                })

    if not rows:
        print("No GCI/Richardson data (need job_0000_n25,n50,n100, job_0001_n25,n50,n100, job_0002_n25,n50,n100, job_0005_n25,n50,n100, job_0006_n25,n50,n100, job_0007_n25,n50,n100).")
        return

    # CSV
    csv_path = out_dir / "gci_richardson_roark_deflection_rotation.csv"
    with open(csv_path, "w", encoding="utf-8") as f:
        f.write("job_id,load_type,QoI,n_fine,n_med,n_coarse,phi_fine,phi_med,phi_coarse,p_obs,phi_ext,Roark,error_ext_Roark_pct,error_phi1_Roark_pct,GCI_12_pct,GCI_23_pct,fine_vs_rich_pct,GCI_23_12_ratio,r_p\n")
        for r in rows:
            f.write(
                f"{r['job_id']},{r['load_type']},{r['QoI']},{r['n_fine']},{r['n_med']},{r['n_coarse']},"
                f"{r['phi_fine']:.12e},{r['phi_med']:.12e},{r['phi_coarse']:.12e},"
                f"{r['p_obs']:.6f},{r['phi_ext']:.12e},{r['Roark']:.12e},"
                f"{r['error_ext_Roark_pct']:.6f},{r['error_phi1_Roark_pct']:.6f},{r['GCI_12_pct']:.6f},{r['GCI_23_pct']:.6f},"
                f"{r['fine_vs_rich_pct']:.6f},{r['GCI_23_12_ratio']:.6f},{r['r_p']:.6f}\n"
            )
    print(f"Saved: {csv_path}")

    # LaTeX table and PDF
    _write_latex_table(out_dir, rows)
    _build_pdf(out_dir)

    # Console summary
    print("\n--- GCI and Richardson extrapolation (Roark vs FEM tip deflection/rotation) ---")
    for r in rows:
        p_str = f"{r['p_obs']:.3f}" if math.isfinite(r["p_obs"]) else "N/A"
        gci12_str = f"{r['GCI_12_pct']:.4f}%" if math.isfinite(r["GCI_12_pct"]) else "N/A"
        gci23_str = f"{r['GCI_23_pct']:.4f}%" if math.isfinite(r["GCI_23_pct"]) else "N/A"
        err_str = f"{r['error_ext_Roark_pct']:.4f}%" if math.isfinite(r["error_ext_Roark_pct"]) else str(r["error_ext_Roark_pct"])
        print(f"  job_{r['job_id']:04d} {r['load_type']} {r['QoI']}: p_obs={p_str} phi_ext={r['phi_ext']:.6e} Roark={r['Roark']:.6e} error_ext={err_str} GCI_12={gci12_str} GCI_23={gci23_str}")
    print("")


if __name__ == "__main__":
    _run_report()
    sys.exit(0)
